### ISSUE TITLE
A lot of mouse input seems to cause poll_event to return None when it should still have events for that frame

### ISSUE THREAD

**Issue by LaylBongers** [PistonDevelopers/glutin_window#122]
My best guess is that it's caused by this line:
https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L378

And that some event is being raised in glutin that's not being handled, causing None to be returned, which will be interpreted as no more events being left even if there still are. The result of this is that game input will lag a lot even if framerate is smooth.

**Comment by bvssvni** [comment]
It should probably be replaced by a `while let Some(e) = ... { ... }` loop.

**Comment by bvssvni** [comment]
I'm investigating this closer because we probably should add some more events to the Piston core.

**Comment by LaylBongers** [comment]
Regardless of fixing the offending event itself being handled, it probably shouldn't be returning None on not recognizing the event regardless, right now it's causing a 1 minute (**!**) long delay if someone moves the mouse for just a few seconds.

**Comment by bvssvni** [comment]
OK.
