### ISSUE TITLE
Scaling issue in 0.48

### ISSUE THREAD

**Issue by 0e4ef622** [PistonDevelopers/glutin_window#145]
A window in a HiDPI display seems to scale incorrectly. Moving the window to a standard dpi display causes the window to resize and scale correctly, but it's never right on the HiDPI display. This wasn't really an issue in 0.47 since the window didn't try to resize/rescale when moved between monitors that have different DPI's.

On the HiDPI display (incorrect).
![incorrect](http://i.imgur.com/QK3tnRu.png)

On the standard dpi display (correct).
![correct](http://i.imgur.com/1T1SIk7.png)

[code](https://gist.github.com/0e4ef622/085fcd4e0cb1b51e431b113b48474723)

I am running Arch Linux and using the i3 window manager.
```
$ uname -a
Linux anpotato 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
```

Possibly related to https://github.com/tomaka/glutin/issues/1068

**Comment by francesca64** [comment]
This isn't related to tomaka/glutin#1068. While I'm not familiar with Piston's stack, it looks like the rendering isn't accounting for the DPI factor at all. I'd look into whatever's generating your matrices, since that's where the problem should be.

**Comment by 0e4ef622** [comment]
I tested on Windows, and it seems to be the opposite. It's correct on the HiDPI display, but not the standard dpi display.

**Comment by bvssvni** [comment]
Notice that drawing is set up in frame buffer coordinates by 2D backends, not user coordinates, as @francesca64 pointed out.

**Comment by bvssvni** [comment]
Do you get the same bug with the SDL2 or GLFW backend?

**Comment by 0e4ef622** [comment]
The bug doesn't occur in SDL2 nor GLFW in that the position isn't blatantly wrong like with glutin, but SDL and GLFW don't appear to scale with DPI. i.e. the square is smaller.

**Comment by bvssvni** [comment]
So, Glutin detects DPI change and resizes the window.

What happens if you add `c.transform.scale(dx, dy)` where `dx, dy` are `Window::draw_size()` divided by `Window::size()`?

**Comment by 0e4ef622** [comment]
Adding
```rust
let size = window.size();
let draw_size = window.draw_size();
let dx = draw_size.width as f64 / size.width as f64;
let dy = draw_size.height as f64 / size.height as f64;
c.transform = c.transform.scale(dx, dy);
```
made the square bigger, and the position is still wrong.

**Comment by bvssvni** [comment]
I think it is likely that the bug detecting code triggers this bug. We could merge https://github.com/PistonDevelopers/glutin_window/pull/147, release a new patch, and yank the version if people get problems.

**Comment by bvssvni** [comment]
For some reason I can't find the original issue to this PR: https://github.com/PistonDevelopers/glutin_window/pull/136

**Comment by bvssvni** [comment]
@0e4ef622 how does the `dx, dy` modification work with your patch? Is it scaled right?

**Comment by bvssvni** [comment]
It might be that you should scale with `1/dx, 1/dy` instead.

**Comment by bvssvni** [comment]
Link to previous bug fix: https://github.com/PistonDevelopers/glutin_window/issues/137

**Comment by bvssvni** [comment]
If my intuition is correct, the position should be affected by the bug, not the size. So, with the right matrix set up the rectangle should be at the right size and position correctly with the patch.

If this is correct, then there is a bug, and merging the patch will either fix the problem for everyone or lead to a Heisen-bug (a bug fix that triggers another bug).

**Comment by 0e4ef622** [comment]
Scaling by 1/dx and 1/dy with my patch makes the red square the same size as with the GLFW backend and SDL2 backend without the scaling.

**Comment by bvssvni** [comment]
Hmm... that doesn't sound right. Do you have screenshots comparing SDL2 vs Glutin?

**Comment by 0e4ef622** [comment]
![screenshot](http://i.imgur.com/AvuUsvB.png)

EDIT: I don't know what's wrong with the title .-.

**Comment by 0e4ef622** [comment]
![screenshot](http://i.imgur.com/yxhJTxk.png)

Another screenshot comparing SDL2 and glutin_window 0.47.

**Comment by bvssvni** [comment]
I'm not sure how to interpret those screenshots.

The general idea is that if the resolution gets larger, drawing should stay in pixel coordinates. This how 2D backends behave by default today, but it might change in future. So, the size of the rectangle should stay the same in pixel coordinates.

However, somehow the rectangle size is *corrected* after applying a matrix transform. This confuses me.

**Comment by 0e4ef622** [comment]
Glutin is the only backend that appears to scale with dpi, at least on Linux. All the screenshots we're on a 144 dpi display.

**Comment by 0e4ef622** [comment]
A side effect of this is text appears blurry on high dpi screens since the glyphs are rasterized at the wrong size.

**Comment by bvssvni** [comment]
I think it makes sense to go the route of https://github.com/PistonDevelopers/glutin_window/pull/148, but also remove the stuff which is no longer needed.

**Comment by bvssvni** [comment]
I believe combining the two PRs is the right thing to do. Will make a PR soon.
