### ISSUE TITLE
Allow use of opengles

### ISSUE THREAD

**Issue by OptimisticPeach** [PistonDevelopers/glutin_window#154]
Use `GlRequest::GlThenGles` rather than using `Specific`:
This would allow people to use opengles with `glutin_window` (Which I have done) without having to modify a local clone.
change [this](https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L83):

    .with_gl(GlRequest::Specific(Api::OpenGl, (major as u8, minor as u8)))

To something more like this: 

    .with_gl(GlRequest::GlThenGles {
        opengl_version: (major as u8, minor as u8),
        opengles_version: (major as u8, minor as u8),
    })

It doesn't matter if the user chooses opengl or opengles, because this would support both!

**Comment by bvssvni** [comment]
I think this is a good idea and we should do what you suggested.
