### ISSUE TITLE
Capturing glutin events not supported by piston

### ISSUE THREAD

**Issue by kaikalii** [PistonDevelopers/glutin_window#163]
There are some event types that `glutin` supports that are not supported by `piston`, namely `glutin::WindowEvent::DroppedFile` and `glutin::WindowEvent::HoveredFile`. I use `piston_window` to wrap `glutin_window`, but it would be nice to have access to these events from `PistonWindow::next`. Would it be possible to pass these events along to a `PistonWindow`, perhaps through a `Event::Custom`?

**Comment by bvssvni** [comment]
Alternative is to add support for these events in Piston, then update glutin_window. PRs are welcome!

**Comment by kaikalii** [comment]
#165 has been merged, so I'm closing this.
