### ISSUE TITLE
GlutinWindow needs dependency updates

### ISSUE THREAD

**Issue by ghost** [PistonDevelopers/glutin_window#53]
I think there is a dependency conflict between `piston` pulling `pistoncore-window 0.6.0` and `pistoncore-glutin_window` pulling `pistoncore-window 0.5.0` like with the following errors:
https://gist.github.com/stratact/295bfe6db234948c3795

**Comment by ghost** [comment]
@bvssvni, any reason to keep this open?

**Comment by bvssvni** [comment]
No.

Closed by https://github.com/PistonDevelopers/glutin_window/pull/55
