### ISSUE TITLE
Resize events aren't delivered on OS X

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/glutin_window#88]
Here's the [relevant issue in glutin](https://github.com/tomaka/glutin/issues/445). I've only confirmed this on OS X 10.10.

The reason for this seems to be that cocoa (via glutin) requires that the user declares a `resize_callback` for resizing the window, rather than emitting an event as for all other events.

Events are blocked during resize on OS X within cocoa itself. Cocoa _also_ requires that GL rendering occurs on the main thread (at least I'm pretty sure). I'm unsure whether or not events could be polled from a thread other than the main thread. Either way, any multi-threaded solutions are probably too heavy-weight for this lib or glutin.

For now, I guess we could have a special case for OS X where we create our own `Resize` events by comparing window sizes as @bvssvni suggests [here](https://github.com/tomaka/glutin/issues/445#issuecomment-124846474), however this will only provide the event after the mouse is released and the event loop is unblocked, meaning that we still won't have live `Resize` or `Render` events during resizing.

I don't have any great solutions for this yet, just thought I'd post an issue to keep track.

**Comment by bvssvni** [comment]
piston_window checks the size of the frame buffer against the window: https://github.com/PistonDevelopers/piston_window/blob/master/src/lib.rs#L259, but doesn't emit resize events.

If glutin_window does this check instead, and it's consistent across the window backends, then piston_window could use resize events to change frame buffers.
