### ISSUE TITLE
Exclude title bar from size of window

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glutin_window#9]
See https://github.com/PistonDevelopers/piston-examples/issues/184

The title bar should be excluded from the size.

**Comment by bvssvni** [comment]
The same should be done for cursor coordinates. The cursor position should be in the inner window size, but in user coordinates and not in draw coordinates.

**Comment by Potpourri** [comment]
`Size([w, h])` shouldn't include title and border?

**Comment by bvssvni** [comment]
It uses `get_outer_size` for `Size` https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L135

**Comment by bvssvni** [comment]
This should be replaced with `get_inner_size` and scaled to user space.

Problem is how to scale it?

**Comment by bvssvni** [comment]
We could use `hidpi_factor` https://github.com/tomaka/glutin/blob/4dc14280a8f192961a46e70267cf7eae78416582/src/window.rs#L409
